//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DepthCamera
{
    [Serializable]
    public class CameraInfoMsg : Message
    {
        public const string k_RosMessageName = "sensor_msgs/CameraInfo";
        public override string RosMessageName => k_RosMessageName;

        public float fov;
        public float aspect;
        public float nearClip;
        public float farClip;

        public CameraInfoMsg()
        {
            this.fov = 0;
            this.aspect = 0;
            this.nearClip = 0;
            this.farClip = 0;
        }

        public CameraInfoMsg(float fov, float aspect, float nearClip, float farClip)
        {
            this.fov = fov;
            this.aspect = aspect;
            this.nearClip = nearClip;
            this.farClip = farClip;
        }

        public static CameraInfoMsg Deserialize(MessageDeserializer deserializer) => new CameraInfoMsg(deserializer);

        private CameraInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fov);
            deserializer.Read(out this.aspect);
            deserializer.Read(out this.nearClip);
            deserializer.Read(out this.farClip);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fov);
            serializer.Write(this.aspect);
            serializer.Write(this.nearClip);
            serializer.Write(this.farClip);
        }

        public override string ToString()
        {
            return "CameraInfoMsg: " +
            "\nfov: " + fov.ToString() +
            "\naspect: " + aspect.ToString() +
            "\nnearClip: " + nearClip.ToString() +
            "\nfarClip: " + farClip.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            //MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
